import crypto from "node:crypto";

// Generates a unique, user-facing payment reference like DQR-3F9A2C1B that the
// customer includes when paying via InstaPay, so payments can be matched.
export function generatePaymentReference() {
  const random = crypto.randomBytes(4).toString("hex").toUpperCase();
  return `DQR-${random}`;
}

// One-time check for a payment reference idempotency / confirmation lookup.
export function isPlausibleInstaPayRef(ref) {
  return typeof ref === "string" && /^[A-Za-z0-9-]{6,32}$/.test(ref);
}

// Builds the text shown on the payment QR. This is a simple text QR for the
// MVP (a real InstaPay merchant QR generated by your bank would be embedded
// here instead); the wallet number is always shown alongside it.
export function buildPaymentQrText({ wallet, amountEGP, reference }) {
  return `InstaPay: pay EGP ${amountEGP} to ${wallet} — reference ${reference}`;
}